[package]
name = "models_settings"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "models_settings"
path = "src/lib.rs"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }