//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod appointment_events;
pub mod appointments;
pub mod days;
pub mod medical_records;
pub mod password_reset;
pub mod pet_events;
pub mod pet_type_events;
pub mod pet_types;
pub mod pets;
pub mod service_events;
pub mod services;
pub mod session_events;
pub mod sessions;
pub mod special_date_events;
pub mod special_dates;
pub mod unavailable_hour_events;
pub mod unavailable_hours;
pub mod user_events;
pub mod user_role_events;
pub mod user_roles;
pub mod users;
pub mod work_day_events;
pub mod work_days;
