//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "pets"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub pet_id: i32,
    pub pet_type_id: Option<i32>,
    pub name: Option<String>,
    pub creation_date: Option<DateTime>,
    pub latest_update_date: Option<DateTime>,
    pub user_id: Option<i32>,
    pub additional_comments: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    PetId,
    PetTypeId,
    Name,
    CreationDate,
    LatestUpdateDate,
    UserId,
    AdditionalComments,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    PetId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Appointments,
    MedicalRecords,
    PetTypes,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::PetId => ColumnType::Integer.def(),
            Self::PetTypeId => ColumnType::Integer.def().null(),
            Self::Name => ColumnType::Text.def().null(),
            Self::CreationDate => ColumnType::DateTime.def().null(),
            Self::LatestUpdateDate => ColumnType::DateTime.def().null(),
            Self::UserId => ColumnType::Integer.def().null(),
            Self::AdditionalComments => ColumnType::Text.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Appointments => Entity::has_many(super::appointments::Entity).into(),
            Self::MedicalRecords => Entity::has_many(super::medical_records::Entity).into(),
            Self::PetTypes => Entity::belongs_to(super::pet_types::Entity)
                .from(Column::PetTypeId)
                .to(super::pet_types::Column::PetTypeId)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::UserId)
                .into(),
        }
    }
}

impl Related<super::appointments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appointments.def()
    }
}

impl Related<super::medical_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalRecords.def()
    }
}

impl Related<super::pet_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PetTypes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
