//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "services"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub service_id: i32,
    pub name: Option<String>,
    pub duration: Option<i32>,
    pub creation_date: Option<DateTime>,
    pub is_enabled: Option<bool>,
    pub latest_update_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    ServiceId,
    Name,
    Duration,
    CreationDate,
    IsEnabled,
    LatestUpdateDate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ServiceId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Appointments,
    SpecialDates,
    UnavailableHours,
    WorkDays,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ServiceId => ColumnType::Integer.def(),
            Self::Name => ColumnType::Text.def().null(),
            Self::Duration => ColumnType::Integer.def().null(),
            Self::CreationDate => ColumnType::DateTime.def().null(),
            Self::IsEnabled => ColumnType::Boolean.def().null(),
            Self::LatestUpdateDate => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Appointments => Entity::has_many(super::appointments::Entity).into(),
            Self::SpecialDates => Entity::has_many(super::special_dates::Entity).into(),
            Self::UnavailableHours => Entity::has_many(super::unavailable_hours::Entity).into(),
            Self::WorkDays => Entity::has_many(super::work_days::Entity).into(),
        }
    }
}

impl Related<super::appointments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appointments.def()
    }
}

impl Related<super::special_dates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpecialDates.def()
    }
}

impl Related<super::unavailable_hours::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnavailableHours.def()
    }
}

impl Related<super::work_days::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkDays.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
