//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "sessions"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub session_id: i32,
    pub user_id: Option<i32>,
    pub session_uuid: Option<Uuid>,
    pub is_enabled: Option<bool>,
    pub creation_date: Option<DateTime>,
    pub latest_update_date: Option<DateTime>,
    pub closing_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    SessionId,
    UserId,
    SessionUuid,
    IsEnabled,
    CreationDate,
    LatestUpdateDate,
    ClosingDate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    SessionId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::SessionId => ColumnType::Integer.def(),
            Self::UserId => ColumnType::Integer.def().null(),
            Self::SessionUuid => ColumnType::Uuid.def().null(),
            Self::IsEnabled => ColumnType::Boolean.def().null(),
            Self::CreationDate => ColumnType::DateTime.def().null(),
            Self::LatestUpdateDate => ColumnType::DateTime.def().null(),
            Self::ClosingDate => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::UserId)
                .into(),
        }
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
