//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "unavailable_hours"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub unavailable_hour_id: i32,
    pub service_id: Option<i32>,
    pub date: Option<Date>,
    pub start_time: Option<Time>,
    pub end_time: Option<Time>,
    pub reason: Option<String>,
    pub creation_date: Option<DateTime>,
    pub latest_update_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    UnavailableHourId,
    ServiceId,
    Date,
    StartTime,
    EndTime,
    Reason,
    CreationDate,
    LatestUpdateDate,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    UnavailableHourId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Services,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::UnavailableHourId => ColumnType::Integer.def(),
            Self::ServiceId => ColumnType::Integer.def().null(),
            Self::Date => ColumnType::Date.def().null(),
            Self::StartTime => ColumnType::Time.def().null(),
            Self::EndTime => ColumnType::Time.def().null(),
            Self::Reason => ColumnType::Text.def().null(),
            Self::CreationDate => ColumnType::DateTime.def().null(),
            Self::LatestUpdateDate => ColumnType::DateTime.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Services => Entity::belongs_to(super::services::Entity)
                .from(Column::ServiceId)
                .to(super::services::Column::ServiceId)
                .into(),
        }
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
