//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "work_days"
    }
}

#[derive(
    Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize, Default,
)]
pub struct Model {
    pub work_day_id: i32,
    pub service_id: Option<i32>,
    pub day_id: Option<i32>,
    pub is_enabled: Option<bool>,
    pub creation_date: Option<DateTime>,
    pub latest_update_date: Option<DateTime>,
    pub open_time: Option<Time>,
    pub close_time: Option<Time>,
    pub lunch_from_time: Option<Time>,
    pub lunch_to_time: Option<Time>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    WorkDayId,
    ServiceId,
    DayId,
    IsEnabled,
    CreationDate,
    LatestUpdateDate,
    OpenTime,
    CloseTime,
    LunchFromTime,
    LunchToTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    WorkDayId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Days,
    Services,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::WorkDayId => ColumnType::Integer.def(),
            Self::ServiceId => ColumnType::Integer.def().null(),
            Self::DayId => ColumnType::Integer.def().null(),
            Self::IsEnabled => ColumnType::Boolean.def().null(),
            Self::CreationDate => ColumnType::DateTime.def().null(),
            Self::LatestUpdateDate => ColumnType::DateTime.def().null(),
            Self::OpenTime => ColumnType::Time.def().null(),
            Self::CloseTime => ColumnType::Time.def().null(),
            Self::LunchFromTime => ColumnType::Time.def().null(),
            Self::LunchToTime => ColumnType::Time.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Days => Entity::belongs_to(super::days::Entity)
                .from(Column::DayId)
                .to(super::days::Column::DayId)
                .into(),
            Self::Services => Entity::belongs_to(super::services::Entity)
                .from(Column::ServiceId)
                .to(super::services::Column::ServiceId)
                .into(),
        }
    }
}

impl Related<super::days::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Days.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
